# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 66a04f3336d1baada6367f95ee1b5eefd4f163dae061f89867a65d236753f76873f3d139f1ab36f1da4f5ba36b546602050a61a4b7ceaa46f26aafecc3650592

test:
  secret_key_base: 87d821029d6267c3c9b7b0636c23a65b16e736cfe1a7a8f85a9ac9051063c956ea7673f77fdbe01bd3a2bb83699f6f0dd58f34414300cc18aaf8317b9c48ad10

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
